#!/bin/bash
# Fetches latest Cloudflare IP ranges and updates UFW rules for port 8080.
# Intended to run daily via cron.
# Port 80 is intentionally excluded — it is a honeypot port and must remain open to all.

PORTS="${PORTS:-8080}"
COMMENT="Cloudflare"
TMPFILE=$(mktemp)
trap "rm -f $TMPFILE" EXIT

# Fetch current Cloudflare IP ranges (echo ensures newline between v4 and v6)
curl -sf https://www.cloudflare.com/ips-v4 > "$TMPFILE"
echo >> "$TMPFILE"
curl -sf https://www.cloudflare.com/ips-v6 >> "$TMPFILE"

# Strip carriage returns and blank lines
sed -i 's/\r//; /^$/d' "$TMPFILE"

if [ ! -s "$TMPFILE" ]; then
    echo "ERROR: Failed to fetch Cloudflare IPs. Leaving rules unchanged."
    exit 1
fi

for PORT in $PORTS; do
    echo "Syncing port $PORT..."

    # Get current Cloudflare rules from UFW for this port (extract CIDR ranges)
    CURRENT=$(ufw status | grep "$PORT/tcp.*# $COMMENT" | awk '{print $3}')

    # Remove rules that are no longer in Cloudflare's list
    for cidr in $CURRENT; do
        if ! grep -q "^${cidr}$" "$TMPFILE"; then
            echo "y" | ufw delete allow from "$cidr" to any port $PORT proto tcp 2>/dev/null && echo "Removed: $cidr (port $PORT)" || true
        fi
    done

    # Add any new ranges not already in UFW
    for cidr in $(cat "$TMPFILE"); do
        if ! echo "$CURRENT" | grep -q "^${cidr}$"; then
            ufw allow from "$cidr" to any port $PORT proto tcp comment "$COMMENT" && echo "Added: $cidr (port $PORT)"
        fi
    done
done

echo "Cloudflare UFW rules updated at $(date)"

# --- Optional: regenerate nginx Cloudflare include file ---
# If NGINX_IP_INCLUDE is set, regenerate that file with current Cloudflare allow/deny rules.
# The nginx config should contain: include /etc/nginx/cloudflare_ips.conf;
# Usage: NGINX_IP_INCLUDE=/etc/nginx/cloudflare_ips.conf ./update-cloudflare-ufw.sh
if [ -n "$NGINX_IP_INCLUDE" ]; then
    echo "Updating nginx Cloudflare include file $NGINX_IP_INCLUDE..."
    {
        echo "# Cloudflare IPs — auto-generated by update-cloudflare-ufw.sh on $(date)"
        while IFS= read -r cidr; do echo "allow $cidr;"; done < "$TMPFILE"
        echo "deny all;"
    } > "$NGINX_IP_INCLUDE"
    nginx -t && systemctl reload nginx && echo "nginx reloaded."
fi
